import 'bootstrap'
import './scss/bootstrap.scss'
import './scss/main.scss'
import './scss/first_content.scss'
import './scss/feature-row.scss'
import './scss/header.scss'
import './scss/global.scss'
// import './scss/feature-boxes.scss'
// import './scss/main.scss'
// import './scss/mediaqueries.scss'